title: The Fractality Institute
description: The Fractality Institute for Integrative Science and Philosophy
theme: jekyll-theme-cayman

url: "https://fractality.institute"
baseurl: ""   # keep empty for apex

# Show these pages in the top navbar (Cayman supports header_pages)
header_pages:
  - about.md
  - research.md
  - publications.md
  - people.md
  - contact.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Output a publications collection (nice for cards & permalinks)
collections:
  publications:
    output: true
    permalink: /publications/:slug/

# Sensible Markdown/permalinks
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty

# Add this line at the very end of _config.yml
# Force rebuild: 2025-09-01

# Add these new sections for collections
collections:
  frameworks:
    output: true
    permalink: /frameworks/:path/
  protocols:
    output: true
    permalink: /resources/protocols/:path/
  experiments:
    output: true
    permalink: /experiments/:path/
  governance:
    output: true
    permalink: /governance/:path/